apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080     # set fixed port for kind
  type: NodePort