name: 🚀 Deploy Task3 Node.js App to EC2

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup SSH for EC2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      # Step 3: Copy project files to EC2 using rsync
      - name: Deploy Node.js Code to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key.pem" ./ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }}:/home/${{ secrets.SSH_USERNAME }}/app/

      # Step 4: Install Node.js, dependencies, and restart app with PM2
      - name: Restart Node.js App on EC2
        run: |
          ssh -i ~/.ssh/deploy_key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Install Node.js 22 if not installed
            if ! command -v node > /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Install PM2 globally if not installed
            if ! command -v pm2 > /dev/null; then
              sudo npm install -g pm2
            fi

            # Navigate to app folder
            cd ~/app

            # Kill old Node.js process if running
            pkill -f server.js || true

            # Install dependencies
            npm install

            # Start or restart app with PM2
            pm2 stop task3 || true
            pm2 start server.js --name task3
            pm2 save
          EOF
